/**
 * Engine Configuration
 * Defines all 23 computational engines and their settings
 */

import { EngineConfig, EngineType } from '../types/engine.types';

export const ENGINES_CONFIG: EngineConfig[] = [
  {
    id: 'statistical-engine',
    name: 'Statistical Engine',
    type: EngineType.STATISTICAL,
    url: 'http://localhost:8001',
    version: '1.0.0',
    description: 'Descriptive statistics, hypothesis testing, distributions',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 60000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.0,
    priority: 1,
    capabilities: [
      'descriptive_stats',
      'hypothesis_testing',
      'distributions',
      'correlation',
      'regression',
    ],
    metadata: {},
  },
  {
    id: 'economic-engine',
    name: 'Economic Engine',
    type: EngineType.ECONOMIC,
    url: 'http://localhost:8002',
    version: '1.0.0',
    description: 'Macroeconomic indicators, market analysis, forecasting',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 90000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'macroeconomic_analysis',
      'market_forecasting',
      'economic_indicators',
      'sector_analysis',
    ],
    metadata: {},
  },
  {
    id: 'financial-engine',
    name: 'Financial Engine',
    type: EngineType.FINANCIAL,
    url: 'http://localhost:8003',
    version: '1.0.0',
    description: 'Financial modeling, risk assessment, portfolio optimization',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 120000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 2.0,
    priority: 1,
    capabilities: [
      'financial_modeling',
      'risk_assessment',
      'portfolio_optimization',
      'valuation',
      'derivatives_pricing',
    ],
    metadata: {},
  },
  {
    id: 'strategic-engine',
    name: 'Strategic Engine',
    type: EngineType.STRATEGIC,
    url: 'http://localhost:8004',
    version: '1.0.0',
    description: 'Strategic planning, competitive analysis, scenario planning',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 90000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'strategic_planning',
      'competitive_analysis',
      'scenario_planning',
      'swot_analysis',
    ],
    metadata: {},
  },
  {
    id: 'ml-engine',
    name: 'Machine Learning Engine',
    type: EngineType.MACHINE_LEARNING,
    url: 'http://localhost:8005',
    version: '1.0.0',
    description: 'Classification, regression, clustering, feature engineering',
    enabled: true,
    maxInstances: 4,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 180000,
    retryAttempts: 2,
    retryDelay: 2000,
    weight: 2.5,
    priority: 1,
    capabilities: [
      'classification',
      'regression',
      'clustering',
      'feature_engineering',
      'model_training',
    ],
    metadata: {},
  },
  {
    id: 'dl-engine',
    name: 'Deep Learning Engine',
    type: EngineType.DEEP_LEARNING,
    url: 'http://localhost:8006',
    version: '1.0.0',
    description: 'Neural networks, computer vision, NLP, transfer learning',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 300000,
    retryAttempts: 2,
    retryDelay: 3000,
    weight: 3.0,
    priority: 1,
    capabilities: [
      'neural_networks',
      'computer_vision',
      'nlp',
      'transfer_learning',
      'model_inference',
    ],
    metadata: {},
  },
  {
    id: 'optimization-engine',
    name: 'Optimization Engine',
    type: EngineType.OPTIMIZATION,
    url: 'http://localhost:8007',
    version: '1.0.0',
    description: 'Linear/nonlinear optimization, constraint solving',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 120000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 2.0,
    priority: 1,
    capabilities: [
      'linear_optimization',
      'nonlinear_optimization',
      'constraint_solving',
      'multi_objective_optimization',
    ],
    metadata: {},
  },
  {
    id: 'simulation-engine',
    name: 'Simulation Engine',
    type: EngineType.SIMULATION,
    url: 'http://localhost:8008',
    version: '1.0.0',
    description: 'Monte Carlo, discrete event simulation, agent-based modeling',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 180000,
    retryAttempts: 2,
    retryDelay: 2000,
    weight: 2.0,
    priority: 2,
    capabilities: [
      'monte_carlo',
      'discrete_event_simulation',
      'agent_based_modeling',
      'stochastic_simulation',
    ],
    metadata: {},
  },
  {
    id: 'time-series-engine',
    name: 'Time Series Engine',
    type: EngineType.TIME_SERIES,
    url: 'http://localhost:8009',
    version: '1.0.0',
    description: 'Forecasting, seasonality detection, trend analysis',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 120000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 2.0,
    priority: 1,
    capabilities: [
      'forecasting',
      'seasonality_detection',
      'trend_analysis',
      'anomaly_detection',
    ],
    metadata: {},
  },
  {
    id: 'nlp-engine',
    name: 'NLP Engine',
    type: EngineType.NLP,
    url: 'http://localhost:8010',
    version: '1.0.0',
    description: 'Text analysis, sentiment analysis, entity extraction',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 90000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 1,
    capabilities: [
      'text_analysis',
      'sentiment_analysis',
      'entity_extraction',
      'topic_modeling',
      'text_classification',
    ],
    metadata: {},
  },
  {
    id: 'cv-engine',
    name: 'Computer Vision Engine',
    type: EngineType.COMPUTER_VISION,
    url: 'http://localhost:8011',
    version: '1.0.0',
    description: 'Image classification, object detection, segmentation',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 180000,
    retryAttempts: 2,
    retryDelay: 2000,
    weight: 2.5,
    priority: 1,
    capabilities: [
      'image_classification',
      'object_detection',
      'segmentation',
      'face_recognition',
      'ocr',
    ],
    metadata: {},
  },
  {
    id: 'graph-engine',
    name: 'Graph Analytics Engine',
    type: EngineType.GRAPH_ANALYTICS,
    url: 'http://localhost:8012',
    version: '1.0.0',
    description: 'Network analysis, community detection, path finding',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 120000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'network_analysis',
      'community_detection',
      'path_finding',
      'centrality_measures',
    ],
    metadata: {},
  },
  {
    id: 'geospatial-engine',
    name: 'Geospatial Engine',
    type: EngineType.GEOSPATIAL,
    url: 'http://localhost:8013',
    version: '1.0.0',
    description: 'Geographic analysis, mapping, spatial statistics',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 90000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'geographic_analysis',
      'mapping',
      'spatial_statistics',
      'route_optimization',
    ],
    metadata: {},
  },
  {
    id: 'risk-engine',
    name: 'Risk Assessment Engine',
    type: EngineType.RISK_ASSESSMENT,
    url: 'http://localhost:8014',
    version: '1.0.0',
    description: 'Risk modeling, stress testing, scenario analysis',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 120000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 2.0,
    priority: 1,
    capabilities: [
      'risk_modeling',
      'stress_testing',
      'scenario_analysis',
      'var_calculation',
    ],
    metadata: {},
  },
  {
    id: 'predictive-maintenance-engine',
    name: 'Predictive Maintenance Engine',
    type: EngineType.PREDICTIVE_MAINTENANCE,
    url: 'http://localhost:8015',
    version: '1.0.0',
    description: 'Failure prediction, maintenance scheduling, anomaly detection',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 90000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'failure_prediction',
      'maintenance_scheduling',
      'anomaly_detection',
      'rul_estimation',
    ],
    metadata: {},
  },
  {
    id: 'recommendation-engine',
    name: 'Recommendation Engine',
    type: EngineType.RECOMMENDATION,
    url: 'http://localhost:8016',
    version: '1.0.0',
    description: 'Collaborative filtering, content-based recommendations',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 60000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'collaborative_filtering',
      'content_based_filtering',
      'hybrid_recommendations',
      'personalization',
    ],
    metadata: {},
  },
  {
    id: 'fraud-detection-engine',
    name: 'Fraud Detection Engine',
    type: EngineType.FRAUD_DETECTION,
    url: 'http://localhost:8017',
    version: '1.0.0',
    description: 'Anomaly detection, pattern recognition, risk scoring',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 90000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 2.0,
    priority: 1,
    capabilities: [
      'anomaly_detection',
      'pattern_recognition',
      'risk_scoring',
      'fraud_classification',
    ],
    metadata: {},
  },
  {
    id: 'customer-analytics-engine',
    name: 'Customer Analytics Engine',
    type: EngineType.CUSTOMER_ANALYTICS,
    url: 'http://localhost:8018',
    version: '1.0.0',
    description: 'Segmentation, churn prediction, lifetime value',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 90000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'customer_segmentation',
      'churn_prediction',
      'lifetime_value',
      'behavior_analysis',
    ],
    metadata: {},
  },
  {
    id: 'supply-chain-engine',
    name: 'Supply Chain Engine',
    type: EngineType.SUPPLY_CHAIN,
    url: 'http://localhost:8019',
    version: '1.0.0',
    description: 'Inventory optimization, demand forecasting, logistics',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 120000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'inventory_optimization',
      'demand_forecasting',
      'logistics_optimization',
      'supplier_analysis',
    ],
    metadata: {},
  },
  {
    id: 'pricing-engine',
    name: 'Pricing Engine',
    type: EngineType.PRICING,
    url: 'http://localhost:8020',
    version: '1.0.0',
    description: 'Dynamic pricing, price optimization, elasticity analysis',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 60000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'dynamic_pricing',
      'price_optimization',
      'elasticity_analysis',
      'competitive_pricing',
    ],
    metadata: {},
  },
  {
    id: 'credit-scoring-engine',
    name: 'Credit Scoring Engine',
    type: EngineType.CREDIT_SCORING,
    url: 'http://localhost:8021',
    version: '1.0.0',
    description: 'Credit risk assessment, default prediction, scoring models',
    enabled: true,
    maxInstances: 3,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 90000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 2.0,
    priority: 1,
    capabilities: [
      'credit_risk_assessment',
      'default_prediction',
      'scoring_models',
      'creditworthiness_analysis',
    ],
    metadata: {},
  },
  {
    id: 'insurance-analytics-engine',
    name: 'Insurance Analytics Engine',
    type: EngineType.INSURANCE_ANALYTICS,
    url: 'http://localhost:8022',
    version: '1.0.0',
    description: 'Actuarial analysis, claim prediction, underwriting',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 120000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 2.0,
    priority: 1,
    capabilities: [
      'actuarial_analysis',
      'claim_prediction',
      'underwriting',
      'premium_calculation',
    ],
    metadata: {},
  },
  {
    id: 'document-intelligence-engine',
    name: 'Document Intelligence Engine',
    type: EngineType.DOCUMENT_INTELLIGENCE,
    url: 'http://localhost:8023',
    version: '1.0.0',
    description: 'Document classification, information extraction, OCR',
    enabled: true,
    maxInstances: 2,
    minInstances: 1,
    currentInstances: 0,
    healthCheckInterval: 30000,
    timeout: 120000,
    retryAttempts: 3,
    retryDelay: 1000,
    weight: 1.5,
    priority: 2,
    capabilities: [
      'document_classification',
      'information_extraction',
      'ocr',
      'form_processing',
    ],
    metadata: {},
  },
];

export const DEFAULT_FAILOVER_CONFIG = {
  enabled: true,
  maxRetries: 3,
  retryDelay: 1000,
  backoffMultiplier: 2,
  circuitBreakerThreshold: 5,
  circuitBreakerTimeout: 60000,
  fallbackEngines: [],
};

export const DEFAULT_LOAD_BALANCING_CONFIG = {
  strategy: 'weighted-round-robin' as const,
  weights: {},
  stickySession: false,
  sessionTimeout: 300000,
};
